name: renovate

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  issues: write
  statuses: write

jobs:
  renovate:
    name: Run Renovate
    runs-on: ubuntu-latest

    steps:
      - name: Run Renovate
        uses: renovatebot/github-action@v43.0.14
        env:
          RENOVATE_TOKEN: ${{ secrets.RENOVATE_TOKEN || github.token }}
        with:
          configurationFile: renovate.json
          token: ${{ secrets.RENOVATE_TOKEN || github.token }}
